### ISSUE TITLE
Check for other youtube links with same ID

### ISSUE THREAD

**Issue by Long-Horse** [agschwender/reddited-extension#11]
YouTube videos can have multiple URL variations including standard 1) /watch?v=VIDEOID 2) youtu.be/VIDEOID 3) /watch?v=VIDEOID?t=4m20s 4) /watch?v=VIDEOID&list=PLAYLISTID

As of now, RA only checks the link you are on and unfortunately, it doesn't check if other forms of the URL have been posted. Is this a possible feature to add?

I unintentionally reposted something 3 hours after it was originally posted due to this and I thought of this idea. I think it would be a great thing to add!

**Comment by Long-Horse** [comment]
@agschwender

**Comment by agschwender** [comment]
Actually it looks up the current URL, the `canonical URL` and the `og:url` in the hope of avoiding this. It then strips off the fragment. And lastly it does a stem lookup: those URLs just need to match the start of a posted URL. So it's already doing a lot to clean up the URL to make the match more likely. That said, those short URLs that use a different domain, e.g. `youtu.be`, will not be found. In order to make that match, I'd have to do special casing by domain to add the short URL and doing special casing by domain was something that I generally wanted to avoid.

**Comment by Long-Horse** [comment]
Ok thanks for the explanation.

**Comment by Long-Horse** [comment]
Also in the domain blacklist you added earlier on via my request, there is no saving of the list. If I close the settings page and check later, my blacklisted sites are missing and it still checks on those sites.

**Comment by agschwender** [comment]
Yes, I saw and replied to your comment in the chrome store. I'm unable to reproduce the issue you're describing. Basically, it should just save automatically.

**Comment by agschwender** [comment]
Just looked at the page source and it looks like they publish a shortlink and alternate url too, which includes the youtu.be link and the mobile link. So yeah, I can modify the code to make those checks as well, since it won't involve any special casing by domain.

**Comment by agschwender** [comment]
Added in version 1.3.19.
